baseURL = 'http://renanm.com/'
languageCode = 'en-us'
title = 'renan'
theme = 'anatole'
tableOfContents = true
disqusShortname = "renanm"

[params]
displayMode = "dark" # set the darkmode as default

[services]
  [services.disqus]
    shortname = 'renanm'

[Languages]
  [Languages.en]
  title = "renan"
  weight = 1
  LanguageName = "EN"

  [Languages.pt-br]
  title = "renan"
  description = "Líder em Cybersegurança, com 12+ anos de experiência na industria e apaixonado por construir e quebrar coisas"
  weight = 2
  LanguageName = "pt-br"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "whoami"
  weight = 300
  identifier = "whoami"

  [[menu.main]]
  name = "Career and Projects"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"
  parent = "whoami"

  [[menu.main]]
  name = "$ whoami"
  weight = 300
  identifier = "$ whoami"
  url = "/whoami/"
  parent = "whoami"

