baseURL = 'http://renanfernandes.org/'
languageCode = 'en-us'
title = 'renanfernandes / renanm'
theme = 'anatole'
tableOfContents = true

[params]
displayMode = "dark" # set the darkmode as default

[services]
  [services.disqus]
    shortname = 'renanmathiasfernandes'

[Languages]
  [Languages.en]
  title = "renanfernandes / renanm"
  weight = 1
  LanguageName = "EN"

  [Languages.pt-br]
  title = "renanfernandes / renanm"
  description = "Líder em Cybersegurança, com 12+ anos de experiência na industria e apaixonado por construir e quebrar coisas"
  weight = 2
  LanguageName = "pt-br"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "whoami"
  weight = 300
  identifier = "whoami"

  [[menu.main]]
  name = "Career and Projects"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"
  parent = "whoami"

  [[menu.main]]
  name = "$ whoami"
  weight = 300
  identifier = "$ whoami"
  url = "/whoami/"
  parent = "whoami"

